name: Upload Release Assets

on:
  workflow_dispatch:   # allow manual trigger
  push:
    tags:
      - 'v*'           # trigger when pushing a version tag

jobs:
  upload-assets:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # needed for uploading release assets

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload build artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            .release/*.tar.gz
            .release/*.sha256
            .release/*.sha512
            .release/*.asc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
